let currentUser = null;
let currentProfile = null;
let selectedGroup = null;
let myGroups = [];
let groupChannel = null; // Supabase Realtime channel for current group
let contactSharesChannel = null; // Realtime for "X shared Y with you" toasts
let contactEventsChannel = null; // Realtime for new contacts + selfie updates
let activeTab = 'money'; // Current tab: 'money', 'members', 'constitution', 'chat'
let shareWithContactId = null;
let shareWithContactName = '';
let vouchWithContactId = null;
let vouchWithContactName = '';
let contactSelfieId = null;
let contactSelfieStream = null;
let recentSelfieUploads = {}; // contact_id -> timestamp for suppressing self notifications
let pendingOpenContactId = null; // open this contact detail after app render
let pendingOpenNewestContact = false; // fallback when exact new contact id is unknown
let profileCache = {};   // user_id -> display_name cache for chat
