let currentUser = null;
let currentProfile = null;
let selectedGroup = null;
let myGroups = [];
let groupChannel = null; // Supabase Realtime channel for current group
let contactSharesChannel = null; // Realtime for "X shared Y with you" toasts
let contactEventsChannel = null; // Realtime for new contacts + selfie updates
let contactNotificationsChannel = null; // Realtime for profile picture / met-date toasts
let activeTab = 'money'; // Current tab: 'money', 'members', 'constitution', 'chat'
let activeMainView = 'contacts'; // Current main view: 'contacts', 'groups', 'profile'
let shareWithContactId = null;
let shareWithContactName = '';
let shareWithInitialPhone = false; // pre-checked state for shareChoice modal
let shareWithInitialEmail = false;
let sponsorShareInfoContactId = null;
let sponsorShareInfoContactName = '';
let vouchWithContactId = null;
let vouchWithContactName = '';
let contactSelfieId = null;
let newContactSelfieId = null;
let newContactSelfieContactName = '';
let newContactSelfieStream = null;
let contactSelfiesCache = {}; // contact_id -> array of selfie records
let recentSelfieUploads = {}; // contact_id -> timestamp for suppressing self notifications
let suggestPicContactId = null;
let suggestPicStream = null;
let pendingOpenContactId = null; // open this contact detail after app render
let pendingOpenNewestContact = false; // fallback when exact new contact id is unknown
// Meet-link joiner: show new-contact selfie first; close navigates to sponsor details.
let pendingPostHandshakeSelfieContactId = null;
let pendingPostHandshakeSelfieContactName = null;
let profileCache = {};   // user_id -> display_name cache for chat
let nearbyTrackingInterval = null; // setInterval id for foreground GPS polling
let nearbyTrackingActive = false; // true when at least one contact has notify_nearby
let locationSharesOutbound = {}; // contact_id -> { expires_at }
let locationSharesInbound = {};  // contact_id -> { expires_at }
let locationSharesChannel = null; // Realtime for location_shares changes
let locationSharingInterval = null;
let contactLocationsChannel = null; // Realtime for user_locations of inbound sharers
let contactLocationsPollInterval = null; // Fallback poll of inbound sharers' positions
let shareRemainingTimer = null;
let shareLocationContactId = null;
let shareLocationContactName = '';
let nativeLocationLastPosition = null; // { lat, lng } from native plugin
let nativeLocationLastAt = 0; // Date.now() when nativeLocationLastPosition was captured
